### ISSUE TITLE
Errore Semaforo

### ISSUE THREAD

**Issue by albertorosati** [TryKatChup/SistemiOperativi_QA#1]
Segnalo la mancanza di un ";" nella funzione while alla riga 780.

**Comment by TryKatChup** [comment]
Ho controllato il pdf, e l'utilizzo di ```;``` risulta errato, poiché non si tratta di un ```while(statement)``` vuoto, bensì di un ciclo che presenta al suo interno un' operazione di decremento di una variabile.

Tuttavia, per chiarezza e per buona prassi, ho modificato il documento e inserito le parentesi graffe per indicare l'inizio e la fine del ciclo.

Documentazione sull'uso della sintassi in Java per gli _statement_: 
https://www.oracle.com/java/technologies/javase/codeconventions-statements.html

**Comment by albertorosati** [comment]
Ciao,ti allego uno screenshot dalle slide della professoressa Ciampolini.Come puoi vedere l'istruzione di while è vuota.GrazieIl 25 giu 2020 13:47, Karina Chichifoi <notifications@github.com> ha scritto:

Ho controllato il pdf, e l'utilizzo di ; risulta errato, poiché non si tratta di un while(statement) vuoto, bensì di un ciclo che presenta al suo interno un' operazione di decremento di una variabile.

Tuttavia, per chiarezza e per buona prassi, ho modificato il documento e inserito le parentesi graffe per indicare l'inizio e la fine del ciclo.

Documentazione sull'uso della sintassi in Java per gli statement:

https://www.oracle.com/java/technologies/javase/codeconventions-statements.html

**Comment by TryKatChup** [comment]
Hai ragione, chiedo scusa per l'incomprensione.
Rileggendo la teoria ha effettivamente senso che il while sia vuoto, poiché il valore ```s``` viene incrementato da ```v()``` (due processi ```p()``` e ```v()``` condividono la stessa risorsa ```s```); soltanto quando ```s``` risulta essere maggiore di 0 avviene il decremento del semaforo ```s``` da parte di ```p()```.

Grazie per la segnalazione, provvedo a sistemare il documento. Se hai altre segnalazioni fammi sapere.
