### ISSUE TITLE
fix project organization

### ISSUE THREAD

**Issue by dariodenardi** [TryKatChup/SistemiOperativi_QA#3]
Direi di creare una cartella "img" al cui interno mettere le immagini...l'organizzazione :D

[SistemiOperativi_QA.zip](https://github.com/TryKatChup/SistemiOperativi_QA/files/7995928/SistemiOperativi_QA.zip)

Il codice è aggiornato, bisogna solo ricompilare il .tex, non sono riuscito manco a ricompilarlo...errori dappertutto

PS: Non sono riuscito a fare una pull request :D (dovevo fare per forza una fork)

**Comment by TryKatChup** [comment]
Grazie per la segnalazione. 
È ovvio che ti dia errori, uso il pacchetto `minted` per il codice; se non lo scarichi in locale e se non configuri l'editor con cui compili, dà diversi problemi. Prossima volta prova su Overleaf, fidati, meno mal di testa 😃

**Comment by dariodenardi** [comment]
La prossima volta uso Overleaf 😄 
Ho capito perché usarlo 😆
